apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: delete-pods-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: pod-deleter
  namespace: default
roleRef:
  kind: Role
  name: delete-pods
  apiGroup: rbac.authorization.k8s.io
