kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-configmaps
  namespace: default
subjects:
- kind: ServiceAccount
  name: pod-deleter
  namespace: default
roleRef:
  kind: Role
  name: configmap-reader
  apiGroup: rbac.authorization.k8s.io
