name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Configure gcloud and kubectl
        run: |
          echo '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}' | jq '.' > service_account.json
          gcloud auth activate-service-account --key-file=service_account.json
          gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} --zone ${{ secrets.GKE_CLUSTER_ZONE }} --project ${{ secrets.GCP_PROJECT_ID }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GIT_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ secrets.IMAGE_NAME }}:latest
      
      - name: Install Google Cloud SDK
        run: |
          curl https://sdk.cloud.google.com | bash
          source /root/google-cloud-sdk/path.bash.inc

      - name: Update Google Cloud SDK
        run: |
          gcloud components update

      - name: Apply Kubernetes configuration
        run: |
          kubectl apply -f role.yml
          kubectl apply -f role-configmap.yml
          kubectl apply -f role-write.yml
          kubectl apply -f delete-pods-role.yml
          kubectl apply -f rolebinding.yml
          kubectl apply -f rolebinding-configmap.yml
          kubectl apply -f rolebinding-write.yml
          kubectl apply -f delete-pods-role-binding.yml
          kubectl apply -f service-account.yml
          kubectl apply -f configmap.yml
          kubectl apply -f deployment.yml

      - name: Deploy to GKE
        run: |
          kubectl set image deployment/${{ secrets.DEPLOYMENT_NAME }} ${{ secrets.CONTAINER_NAME }}=ghcr.io/${{ github.repository_owner }}/${{ secrets.IMAGE_NAME }}:latest

